mybatis:
    mapper-locations: classpath:mappers/**/*.xml

server:
    port: 8080
    servlet:
        context-path: /
        session:
            timeout: 30m
            cookie:
                same-site: Lax

spring:
    application:
        name: orangenode
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Abcd1234!
        url: jdbc:mysql://3.34.204.24/orangenode
        username: team3
        hikari:
            poolName: Hikari
            maximum-pool-size: 10
            max-lifetime: 1800000
            auto-commit: false
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: false
    thymeleaf:
        prefix: classpath:/templates

    # 이메일 설정
    mail:
        host: smtp.gmail.com
        port: 587
        username: gudals9677@gmail.com
        password: fxia apsh ihev ctmu
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true

    #jpa 설정
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                use_sql_comments: true

    servlet:
        multipart:
            location: uploads/
            max-file-size: 10MB

    security:
        # 개발시, 배포시 각각 redirect-uri 다름
        oauth2:
            client:
                provider: #네이버와 카카오는 따로 provider 설정 필요
                    kakao:
                        # 인가 코드 받기
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        user-name-attribute: id
                        # 토큰 코드 받기
                        token-uri: https://kauth.kakao.com/oauth/token
                        # 사용자 정보 가져오기
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                #                    google:
                #                        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent

                registration:
                    kakao:
                        # REST API KEY
                        client-id: 8412b8200aef151b8d5e19641b967e1b
                        # 카카오 > 내 애플리케이션 > 카카오 로그인 > 등록된 Redirect URI 사용

                        # 개발시 사용
                        redirect-uri: http://localhost:3000/oauth/callback/kakao

                        # 배포시 사용
                        #redirect-uri: http://ec2-3-35-92-212.ap-northeast-2.compute.amazonaws.com:8080/main
                        #redirect-uri: http://ec2-3-34-204-24.ap-northeast-2.compute.amazonaws.com:3000/oauth/callback/kakao
                        # 배포시 사용 (이거먼저 확인)
                        #redirect-uri: http://3:34:204:24:3000/oauth/callback/kakao

                        authorization-grant-type: authorization_code
                        client-authentication-method: POST
                        client-name: kakao
                        scope:
                            - profile_nickname
                            - profile_image
                            - account_email
                        # 카카오 > 내 애플리케이션 > 카카오로그인 > 보안 > Client Secret
                        client-secret: MLJBEAg6jItFD1ykjdZ7NhhFMwl62HsQ

# 파일 업로드 설정
file:
    upload:
        path: uploads/


img:
    upload:
        path: prodImg/

# ======= 배포 시 정적 리소스의 경로 설정 ========
myServerProd:
    static-resources-path: /home/orangenode/prodImg/
    #static-resources-path: prodImg/
MyServerImg:
    static-resources-pathImg: /home/orangenode/uploads/
    #static-resources-path: uploads/
# =================================
logging:
    level:
        org:
            hibernate:
                sql: debug
                type:
                    descriptor:
                        sql: trace

jwt:
    issuer: gudals9677@gmail.com
    secret: 4XudNUpSmog3lwI9thJFejF7YfBBQnCI

front:
    url: "http://localhost:3000"
    #url: "http://3.34.204.24"